// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiTmyyPErVjSnu8x6IwmWD6iRV9V1DpxI',
    appId: '1:820690181591:web:58a9cc3faa6e92a12e7f92',
    messagingSenderId: '820690181591',
    projectId: 'talk-app-cd9b7',
    authDomain: 'talk-app-cd9b7.firebaseapp.com',
    storageBucket: 'talk-app-cd9b7.firebasestorage.app',
    measurementId: 'G-Z6CZK38H8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF-qHrcOe36K1WozabRKDLKfgB8oJmV7w',
    appId: '1:820690181591:android:e99c9466d6514c5a2e7f92',
    messagingSenderId: '820690181591',
    projectId: 'talk-app-cd9b7',
    storageBucket: 'talk-app-cd9b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx3DE4aojgvP9OZP6wvjrDzjUbKT5q-G4',
    appId: '1:820690181591:ios:99660f5b016f3e4c2e7f92',
    messagingSenderId: '820690181591',
    projectId: 'talk-app-cd9b7',
    storageBucket: 'talk-app-cd9b7.firebasestorage.app',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx3DE4aojgvP9OZP6wvjrDzjUbKT5q-G4',
    appId: '1:820690181591:ios:99660f5b016f3e4c2e7f92',
    messagingSenderId: '820690181591',
    projectId: 'talk-app-cd9b7',
    storageBucket: 'talk-app-cd9b7.firebasestorage.app',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiTmyyPErVjSnu8x6IwmWD6iRV9V1DpxI',
    appId: '1:820690181591:web:fe64744e911da3172e7f92',
    messagingSenderId: '820690181591',
    projectId: 'talk-app-cd9b7',
    authDomain: 'talk-app-cd9b7.firebaseapp.com',
    storageBucket: 'talk-app-cd9b7.firebasestorage.app',
    measurementId: 'G-H6RMHBRYL8',
  );
}
