// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_bdWV3pUsZfM2Hq1iZwJqhmSz3FQgugA',
    appId: '1:381937032528:web:9f054539561ab6e1fb2055',
    messagingSenderId: '381937032528',
    projectId: 'chatting-app-6a8cb',
    authDomain: 'chatting-app-6a8cb.firebaseapp.com',
    storageBucket: 'chatting-app-6a8cb.firebasestorage.app',
    measurementId: 'G-1B8K4MTKCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPl_wR9gTJoWZOQvM13B4FcBTkfgjxbxk',
    appId: '1:381937032528:android:5c4cb3e4bd1ea59efb2055',
    messagingSenderId: '381937032528',
    projectId: 'chatting-app-6a8cb',
    storageBucket: 'chatting-app-6a8cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3_TAez3FTAtqAd56_tJpXRBDRfb5sppA',
    appId: '1:381937032528:ios:13b71aa72bc01a20fb2055',
    messagingSenderId: '381937032528',
    projectId: 'chatting-app-6a8cb',
    storageBucket: 'chatting-app-6a8cb.firebasestorage.app',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3_TAez3FTAtqAd56_tJpXRBDRfb5sppA',
    appId: '1:381937032528:ios:13b71aa72bc01a20fb2055',
    messagingSenderId: '381937032528',
    projectId: 'chatting-app-6a8cb',
    storageBucket: 'chatting-app-6a8cb.firebasestorage.app',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_bdWV3pUsZfM2Hq1iZwJqhmSz3FQgugA',
    appId: '1:381937032528:web:7ce727180b09faa5fb2055',
    messagingSenderId: '381937032528',
    projectId: 'chatting-app-6a8cb',
    authDomain: 'chatting-app-6a8cb.firebaseapp.com',
    storageBucket: 'chatting-app-6a8cb.firebasestorage.app',
    measurementId: 'G-EKMYCH4KZF',
  );
}
